import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "./components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-black">
          <NavbarDemo />
          {children}
          <footer className="text-center text-sm text-white">
            © 2024 fitnesspergram | Email : info@fitnesspergram |<br /> Phone :
            +917086615792 Business Address : uday ka ghar <br />
            --------- @ ----------
          </footer>
        </div>
      </body>
    </html>
  );
}
